### ISSUE TITLE
Unable to run armoryd.py, could not find instance of armorydb at 127.0.0.1:9001

### ISSUE THREAD

**Issue by navdeepio** [goatpig/armoryd#3]
Hi,

OS: Ubuntu 17.10
Armory: 0.96.3

Followed the instructions, tried both the methods(copy files to/from armoryd folder). It results in the same error..

**Comment by navdeepio** [comment]
(ERROR) armoryd.py:3252 - could not find instance of armorydb at 127.0.0.1:9001

**Comment by goatpig** [comment]
You have to run ArmoryDb on your own.
